language: java
sudo: false
install: true
dist: trusty

addons:
  sonarcloud:
    organization: "8k4b4yu8zj93gjyq"
    token:
      secure: "YthaLCPP7YHHGVsioaVrUss0obVRN5Yxp3+eZTQ/bIvaGt9YUV93UjDOtqOEX9vnmXfcgw1UauZQXV/RvkOU3QBmgGzeTGn91nNtaNLnFHMMPobmYtEuf2al65qGGg907LF7JxkUIA/B+p8kMOjstHLcO69BcZ3BsIz955cwLlXulyz5dkzbLD3f3KKTuXSHUY3HTiFKq7OVXpQi9J5jTZYCg+RsaX1FJ3iStA6EIL8vO7DSTMsUCyIbGSRjSGa1HKPf6P4CvyapB+rLMKYqXamY11K6TC5Nr3sGqwr3NRNph05VymbWf68r2Z1WKXhZnhiXjy0T+KN+hWQg0ACyKAWfJkLuEKGEM0/zHXtwoOdTQ7pElwGYBzkwnrWeygPg+d8/5ING+DSX2Q+l3SkOaxmMtU50DWr05AowENn8NVy2KecCbFuBov/YI1aa/aA6nMKBETa7/h36GU3Uuw/RMaGSynPf73sbXI3PXk/cErCvJLE6JuRB91nWTRSudSCauVpA9BDKAqMIvuWvvIDzMrEx9HFUEWIP1ltvNEM4NO+NjCqdHqrYGj+fBECqtjNCa0dp1CkqT8LSTkkJ6nT+UgdtL+W55eaY4CYdl1qLx5qOJhd5iK6XWA3JCc+azrAvCXmnBFyiZaOIj8h+YlW7boxxbPEZRu0VFQIDTK3MVII="

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean install -q
  - mvn clean verify sonar:sonar -Pcoverage -q

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
