language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "Jave-Chen"
    token:
      secure: "Jave-Chen_incubator-dolphinscheduler"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify sonar:sonar -Pcoverage 

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
