on: [push, pull_request]

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      run: |
        wget -O - -q https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.22/checkstyle-8.22-all.jar > /opt/checkstyle.jar
        wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b /opt ${REVIEWDOG_VERSION}
        java -jar /opt/checkstyle.jar "${WORKDIR}" -c "${CHECKSTYLE_CONFIG}"  -f xml \
             | /opt/reviewdog -f=checkstyle \
                  -reporter="${INPUT_REPORTER:-github-pr-check}" \
                  -filter-mode="${INPUT_FILTER_MODE:-added}" \
                  -fail-on-error="${INPUT_FAIL_ON_ERROR:-false}" \
      env:
        workdir: ./
        reviewdog_github_api_token: ${{ secrets.GITHUB_TOKEN }}
        checkstyle_config: style/checkstyle.xml
        reviewdog_version: v0.10.0
        reporter: 'github-pr-check'
