name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
      with:
        reviewdog_github_api_token: ${{ secrets.GITHUB_TOKEN }}
