name: ui_ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: pwd
      run: |
        pwd
        ls -al
    - name: npm install 
      run: |
        mvn -f ./dolphinscheduler-ui/pom.xml --batch-mode \
          verify \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=8k4b4yu8zj93gjyq \
          -Dsonar.projectKey=dolphinscheduler 

