name: ui_ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-sonarqube
        restore-keys: |
          ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-sonarqube
          ${{ runner.os }}-maven-
    - name: pwd
      run: |
        pwd
        ls -al
        cd ./dolphinscheduler-ui
    - name: npm install 
      run: >
        mvn -X --batch-mode 
        verify
        -Dmaven.compile.fork=true 
        -Dmaven.test.skip=true 
        org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
        -Dsonar.host.url=https://sonarcloud.io 
        -Dsonar.organization=8k4b4yu8zj93gjyq 
        -Dsonar.projectKey=dolphinscheduler
        -Dsonar.inclusions=**/*.vue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

